SELECT 
LEFT(BLDG_KEY, 3) AS ColCode
,BLDG_KEY
,SUBSTRING(BLDG_KEY, 4,3) AS Building
,SUBSTRING(BLDG_KEY, CHARINDEX(' ',BLDG_KEY)+1,DATALENGTH(BLDG_KEY)-CHARINDEX(' ',BLDG_KEY)) AS Wing
,BLDG_NAME AS BuildingName
FROM [HPSA].[INVEN].[BLDG_M]
